### ISSUE TITLE
User can be part of multiple groups.

### ISSUE THREAD

**Issue by JaideepPalit** [eclipse/sw360#1163]
### Description

User can be part of multiple groups.

#### Steps followed and expected result

Admin should be able to add secondary groups and roles to user

**Comment by KoukiHama** [comment]
Good enhancement issue!

I want to know this issue is same with the item of @mcjaeger 's comment    "**one should be able to be in multiple organizations**" in https://github.com/eclipse/sw360/issues/178#issuecomment-806211611

Or different from this? 

Sometimes I am confused how "organization" and "group" are different in sw 360.

**Comment by mcjaeger** [comment]
good catch, I believe there are even more issues that 178, but also 178 is kind of asking for more (leaving gorup, etc), which is maybe not only doing multi group.

note that from discussion we have had a couple of points:

* admins shall be in charge for adding groups, not the user itself
* existing group / role attributes remain, becaus eit is important to have them set by external user management
* other groups will be secondary groups to enable project visibility
* admin can also grant role for secondary group, which is not necessarily the same for the primary group

**Comment by mcjaeger** [comment]
note that when working on the user interface in the admin section, this issue may turn obsolete: https://github.com/eclipse/sw360/issues/94
