### ISSUE TITLE
Bug: can't add more than one person to list of moderators with the search dialog

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#134]
<a href="https://github.com/AndreasSchirm"><img src="https://avatars2.githubusercontent.com/u/14091910?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [AndreasSchirm](https://github.com/AndreasSchirm)**
_Friday Jul 21, 2017 at 09:24 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/513_

----

## How to reproduce:
1. Click on modarators in edit mode of a component or project
![img_2017 07 21_ 11 18 51](https://user-images.githubusercontent.com/14091910/28457497-9e19cbf6-6e06-11e7-8b34-48d87da1bef3.png)

2. Search for a person, select it set the check mark to true
![img_2017 07 21_ 10 59 37](https://user-images.githubusercontent.com/14091910/28457052-e5dc8bf6-6e04-11e7-8443-aa94b11e810a.png)
3. repeat search **without** closing the dialog for another person and try to add them

## Actual Result:
The person added first will be deleted from list in the search dialog
![img_2017 07 21_ 11 15 02](https://user-images.githubusercontent.com/14091910/28457313-ec02f5b4-6e05-11e7-8b1d-9939bae27143.png)

## Actual Workaround
1. To add more than one person to the list of moderators I select only one.   
2. Close the search dialog with "select" button . This will update the list.  
3. After that I have to open the search dialog again to add a single person
  
**From my point of view this is very time consuming and needs to be fixed.**

## Expected behavior:
The search dialog can add more than one person to the list of moderators.

**Comment by imaykay** [comment]
The user picker is a general component which is used all over the application. Even though I think this feature (it is not really a bug for me) is a good idea, I just wanted to make sure that we want to have it in every multi user picker.

Beside from this question, what is the concrete flow? I would strive for something where just the (un-)tick of the checkbox changes the data. Do we want to reorder the rows as well on every (un-)tick so that every picked user is in first few rows? Or just when opening the dialog and each time hitting the search button?
BTW: There is no data saved while still in the edit mode of the project/component/release. So the change would only result in the update frequency of the javascript model on the page.

@mcjaeger preferences?

**Comment by mcjaeger** [comment]
(from discussion)
* yes multi select is Ok for affecting places (user and license selection)
* maybe some styling optimisation to reduce dead space in the select button area, making search and reset same height as text field, both button same width)

**Comment by imaykay** [comment]
Ready for test.
