### ISSUE TITLE
Allow checked/unchecked state of Licenses

### ISSUE THREAD

**Issue by maierthomas** [eclipse/sw360#190]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Friday Nov 10, 2017 at 18:31 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/679_

----

It should be possible to have licenses associated with a state that indicates whether this license is already gone through a clearing process. (Is required to mark licenses imported from other sources such as BDP)

**Comment by blaumeiser-at-bosch** [comment]
Former comment is not relevant anymore, requirement has been detailed with customer:

As  a project developer I want to process an open source component/release with a license not stored in the license db so far without further approval. The goal is to be able to work with the component release to enable traceability between projects and the release even prior to an explicit clearance of the component and its license.

Criteria for success: 

* A new license can be added by a developer without the need to  consult another person. This could be done manual entry of the license information using the ui.
* Any created license is marked as "unchecked".
* A license marked as "unchecked" can be used as any license. A license administrator can process the license and switch the state  to "checked". This includes an approval of the license and a completion of the license information according to the organizations oss process,  e.g., an approved list of obligations to follow.
* A user needs the possibility of a report, so that he  can identify unchecked licenses and process them according to the organizations oss process.

Hint: The feature as such does not imply any support towards a local process, i.e., the way unchecked licenses affect the release process of a  project resp. the approval process of a license. The local processing  of an unchecked license has to be defined in an organizations oss process and can only rely on the state information implied by this feature.

Hint: The feature is not meant to provide release relvant data. It is used as an intermediate state during development to use features of SW360 without complete, approved information about the component. But information available should be stored, so that an approval process gets all available information out of SW360.
