### ISSUE TITLE
Command "vagrant up" exits with error : Couldn't open file /C:/sw360/sw360vagrant-master/sw360-single/sw360-xenial

### ISSUE THREAD

**Issue by aravindbn** [eclipse/sw360#305]
$ vagrant up
Bringing machine 'sw360-single' up with 'virtualbox' provider...
==> sw360-single: Box 'sw360-xenial' could not be found. Attempting to find and install...
    sw360-single: Box Provider: virtualbox
    sw360-single: Box Version: >= 0
==> sw360-single: Box file was not detected as metadata. Adding it directly...
==> sw360-single: Adding box 'sw360-xenial' (v0) for provider: virtualbox
    sw360-single: Downloading: sw360-xenial
    sw360-single:
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /C:/sw360/sw360vagrant-master/sw360-single/sw360-xenial

When executed vagrant up command, getting the above error. Any help on this ?

**Comment by alexbrdn** [comment]
The base box is missing. That means you didn't build it or it did not get registered with vagrant. I'd wager that `generate-box.sh` didn't exit cleanly.

You'll have to kick `generate-box.sh` until `vagrant box list`shows sw360-xenial.

**Comment by aravindbn** [comment]
Command ./generate_box.sh is throwing an error : 
$ ./generate_box.sh
No previously created folder found, moving on.
-[] Destroy old box (if created previously and script exited with failure)
==> sw360-xenial: VM not created. Moving on...
-[] Create and provision new box
Bringing machine 'sw360-xenial' up with 'virtualbox' provider...
==> sw360-xenial: Importing base box 'xenial-server-cloudimg-amd64-vagrant'...
==> sw360-xenial: Matching MAC address for NAT networking...
==> sw360-xenial: Setting the name of the VM: sw360-xenial
==> sw360-xenial: Clearing any previously set network interfaces...
==> sw360-xenial: Preparing network interfaces based on configuration...
    sw360-xenial: Adapter 1: nat
==> sw360-xenial: Forwarding ports...
    sw360-xenial: 22 (guest) => 2222 (host) (adapter 1)
==> sw360-xenial: Running 'pre-boot' VM customizations...
==> sw360-xenial: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "dec661a3-cec4-4f85-bd67-31d8c0905cdf", "--type", "headless                                         "]

Stderr: VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap,                                            interface IConsole

**Comment by mcjaeger** [comment]
I think it is not an error connected with sw360. Likely, it is because VirtualBox looks for some capabilities of your processor and your hardware does not provide these.

In most of the cases I have seen this error it was about enabling VT-x in the BIOS of your machine:

https://askubuntu.com/questions/779277/when-using-vagrant-stderr-vboxmanage-error-vt-x-is-not-available-verr-vmx-no

https://stackoverflow.com/questions/5482223/vt-x-is-not-available-when-i-start-my-virtual-machine#13147447

https://forums.virtualbox.org/viewtopic.php?t=58820

In most of the case from these cases, the machines were locked not to enable VT-x for security reasons by the owners of the machine.

PS. as a general technique I recommend also to try to take the error message, in this case "VBoxManage.exe: error: VT-x is not available" is worth a try and use this with the search engine of your choice.
