### ISSUE TITLE
Does SW360 work with openjdk > 8 ?

### ISSUE THREAD

**Issue by maxhbr** [eclipse/sw360#400]
We should think about whether SW360 can be compiled or executed with a openjdk version greater than 8

**Comment by lepokle** [comment]
I'm on it (Assignment is currently not possible).

**Comment by lepokle** [comment]
Results for now:
- SW360 cannot be compiled using JDK >8 due to Thrift 0.9.2. The reason is that Thrift 0.9.2 adds the annotation `javax.annotation.Generated` annotation which is not part of JDK >8 anymore. As far as I can see this annotation is not used by us. Therefore I would suggest to wait until the upgrade of Thrift in order to be able to switch off the annotation. 
- Following the compatibility matrix of Liferay, neither Liferay version 6 nor 7  is compatible with JDK >8. If this will change in the future or if it is working though is unclear. There are blog posts from liferay about the future of Java, see https://community.liferay.com/de/blogs/-/blogs/liferay-jdk-compatibility-roadmap or https://community.liferay.com/de/blogs/-/blogs/the-future-of-java-for-java-and-liferay-developers. However they state in the latter that OpenJDK 8 will be supported at least until 2023 by RedHat. I suppose that this message also includes that the need for compatibility with OpenJDK >8 is very low and nothing will be changed. In any case I would wait until the update to Liferay 7 before continuing to test OpenJDK version >8.

**Comment by lepokle** [comment]
I'm no longer on it now.

**Comment by lepokle** [comment]
@mcjaeger  Maybe we should move this in the work package after the liferay upgrade.

**Comment by mcjaeger** [comment]
documented here:
* OpenJDK 11
* LF 7.3
* thrift 0.13
