### ISSUE TITLE
CVE search update network issue

### ISSUE THREAD

**Issue by longnv519** [eclipse/sw360#402]
By default, cve search service get data from "cve.circl.lu". Some system doesn't support for proxy setting then cve search automation will be broken. Off course, it can't pass through the proxy and show exception:
```
CveSearchGuesser:57 - cve.circl.lu
 java.net.UnknownHostException: cve.circl.lu
```

Note: I'm working in master branch of latest commited version.

**Comment by maxhbr** [comment]
### If you live behind a proxy and you have a working proxy configuration
The query to `cve.circl.lu` is issued at https://github.com/eclipse/sw360/blob/0462d8e48740484748f0bef6279addc442d188f6/backend/src/src-cvesearch/src/main/java/org/eclipse/sw360/cvesearch/datasource/CveSearchApiImpl.java#L54

This call should be aware of the system proxy settings. So if you pass a correct proxy configuration to the JVM, it should work. This can be done via the `$JAVA_FLAGS` (or java command line arguments):
```
JAVA_FLAGS=-Dhttp.proxyHost=10.1.2.3 -Dhttp.proxyPort=8080 -Dhttp.nonProxyHosts="localhost|127.0.0.1"
```
If you have a more complicated proxy setup, which needs e.g. NTLM authentication, it might be a good idea to have a look at cntlm as it adds NTLM authentication on-the-fly.

For tomcat you might have to configure it in the corresponding `bin/catalina.sh`.

### If you live behind a proxy and you do not have a proxy configuration which is allowed to talk to cve.circl.lu
In this case our cve-search service will not work, since there is no way to receive the necessary information.

### Alternative: run cve-search locally
Another alternative might be to run the cve-search server locally. This instance then still has to connect with the internet via some proxy, but SW360 would directly talk to the local server. And cve-search has also the possibility for a configured proxy https://github.com/cve-search/cve-search/blob/550af3dde5b0542349981afe65470deb5cf4e0c9/etc/configuration.ini.sample#L35-L37

**Comment by longnvtoshiba** [comment]
Yeah, i'm living behind a complicated proxy. I created "/sw360/net-proxy.properties", which contain variables like "http.proxyPort", "http.proxyUser",... In java source code(src-cvesearch), i get data in the properties file and use it as proxy configure values. Look like:
`
System.setProperty("http.proxyHost", proxyProperties.getProperty("http.proxyHost"));
System.setProperty("http.proxyPort", proxyProperties.getProperty("http.proxyPort"));
				
Authenticator.setDefault(new Authenticator() {
        @Override
        public PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(proxyProperties.getProperty("http.proxyUser"), 
                        proxyProperties.getProperty("http.proxyPassword").toCharArray());
        }
});`

In fact, this configure did not pass through https. So i changed the query string https -> http then everything working as well. How do you think?

**Comment by maxhbr** [comment]
There is a man in the middle proxy, which breaks up the TLS encryption. To get it working you need to trust the (root) certificate of your proxy (via the java keystore).

**Comment by longnvtoshiba** [comment]
I don't exactly get it. But i think my way is a great choice for proxy issue.
I can publish a patch file for this if you want to.

**Comment by longnv519** [comment]
Thanks alot @maxhbr 
Now, we don't need the proxy configuration any more. Please help me to close this issue.
