### ISSUE TITLE
Check if getTodoIdentifier can be removed.

### ISSUE THREAD

**Issue by lepokle** [eclipse/sw360#585]
PR #517 removed the todoid from the todos. However it has still to be checked which parts of the code can be removed as well.

See comments for more information: https://github.com/eclipse/sw360/pull/517/files#diff-a06e606f8c3ddf41748827fc37910bc8L75.

**Comment by mcjaeger** [comment]
Hm, discussion in the PR https://github.com/eclipse/sw360/pull/517/files#diff-a06e606f8c3ddf41748827fc37910bc8L75 I have almost forgotten (very special for me).

However, I think the implementation was dropped and rewritten later as it turned out to be unusable or not the shape to be corrected. Can close this issue as well then.
