### ISSUE TITLE
Merge Components misses fields

### ISSUE THREAD

**Issue by mcjaeger** [eclipse/sw360#627]
During liferay 7 testing it became apparent that some fields are not covered (maybe anymore):

* ~~Component type~~
* ~~Component category~~
* Owner Country

**Comment by lepokle** [comment]
@mcjaeger The component name is not merged as well. Is that intentional or is it a bug?

**Comment by lepokle** [comment]
I think we shouldn't allow merging the name. Normally you can merge into a component which name you would to retain. In other cases you could rename the component afterwards.

Allowing to merge has the following drawback: We have a constraint that prevents duplicate component names.
When merging components, first the source component is merged into the destination and then saved. Afterwards the source component is deleted. If the component name would have been changed to the source component, an error would be thrown because the name would then be duplicate (source and destination). In addition it would be a bad idea to remove the source component first to prevent this error. You will lost the source component in case of errors.
Therefore an extended workflow would be needed to merge the name:
1. merge component except of the name
2. delete source
3. rename destination

I'm not sure if that is really worth it since components can be renamed after merge as well.
