### ISSUE TITLE
The maven build possibly creates inconsistent or outdated artifacts

### ISSUE THREAD

**Issue by maxhbr** [eclipse/sw360#655]
Due to the version being a variable in the maven pom files, maven is no longer able to find the sw360 libraries in the local folder and always pulls them from the local repository. This results in the following unexpected behaviors:

## usage of outdated libraries
If one
- has previously called `mvn install` on top level,
- then made changes in `src-common` and
- then only calls commands like `mvn package ...`

the following behavior can be observed:
- `src-common` gets recompiled but
- all modules depending on `src-common` still use the outdated one taken from the local repository and thus the changes get not used nor deployed.

## race conditions
If multiple SW360 states are build simultaneously with `mvn install` the resulting state is determined by race conditions. E.g. if one compiles and `src-common` gets replaced or updated in the local repository at the same time, it is not clear which version was used in the resulting artifact.

## Only `mvn package` is not enough
If one has never called `mvn install` on top level, one can also not run `mvn package` in submodules. (I am unsure whether this was possible previously.)

# Possible mitigation:
Always use `mvn install` and do not build multiple SW360 repos at the same time.

**Comment by lepokle** [comment]
# Test described issue
I don't think this is a consequence of using a variable for the version. I've made the following test:

1. Removed all SW360 artifacts from `~/.m2/repository/org/eclipse/sw360`
1. Checkout tag `sw360-3.3.0-M1`. This tag does not yet contain the `revision` variable
1. Do `mvn package` in top level folder. All packages are build successfully
1. as expected, no packages have been put into `~/.m2/repository/org/eclipse/sw360`
1. go into `backend/src-common`
1. Do `mvn package`

This fails with
```
[ERROR] Failed to execute goal on project src-common: Could not resolve dependencies for project org.eclipse.sw360:src-common:jar:3.3.0-M1: The following artifacts could not be resolved: org.eclipse.sw360:exporters:jar:3.3.0-M1, org.eclipse.sw360:datahandler:jar:3.3.0-M1, org.eclipse.sw360:datahandler:jar:tests:3.3.0-M1, org.eclipse.sw360:build-configuration:jar:3.3.0-M1, org.eclipse.sw360:build-configuration:jar:tests:3.3.0-M1: Failure to find org.eclipse.sw360:exporters:jar:3.3.0-M1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

# Analysis
This shows that even before the change the execution of `mvn install` was necessary because maven just does not look in the local build folders if you just build a submodule from the submodule itself.

It seems that the described behavior is default maven behavior, with or without using a variable for the version number. It seems to be the nature of multimodule projects.

# Solution
There is another way of building single modules by respecting all dependencies and taking the correct files in any case (whether there a are files with the same version in the local repository or not). The command has always to be run from the toplevel directory.
```
mvn package -pl backend/src-common -am
```
This command builds all dependencies from the module to build as well. It works in the above test.
This seems to be annoying at a first glance but to be honest, we all were sometimes wrong in the past when we thought we know which modules to rebuild. The time searching a bug from taking wrong dependencies is much more than the building time for dependencies.

# Reference
Using a variable im `pom.xml` is an official supported feature of maven: https://maven.apache.org/maven-ci-friendly.html. Even the multimodule setup is described there. Therefore I think this feature is save to use.

**Comment by maxhbr** [comment]
Thank you for that extensive check.

But I think you have tested something different. I think of the case where I made changes to `src-common`, rebuild everything with `mvn package` and then something depending on `src-common` used the old `src-common` from the local repository, instead of the new in the local folder.

If you cleanup the local repository it is clear that there is nothing that could be taken by maven.

To test it you would build with `mvn install`, change something in `src-common` which has visible effects, and then build with `mvn package` and verify the visible changed effect.

**Comment by lepokle** [comment]
This has been tested as well. If you are running mvn from a submodule directory, local files from dependencies are never taken. 

On the other side, using the correct command from toplevel always takes the local files independent of the local repository. 


-----Original Message-----

**Comment by maxhbr** [comment]
I am not runing mvn from a subfolder here. Always top level and always all modules.

**Comment by lepokle** [comment]
Which maven version are you running? Mine is 3.6.2. I've done the following test on master:

1. Delete local repository
1. Run `mvn install` in toplevel directory
1. Checked that local repository contains built artifacts
1. Change `log4j.properties` in `src-common`
1. Run  `mvn package` in toplevel directory
1. Checked artifact of `src-common`: ok, contains changed file
1. Checked artifact of `svc-attachements`: ok, contains changed `src-common`

So everything worked as expected.

**Comment by maxhbr** [comment]
Ok, that is exactly the where I had problems. I will reproduce it locally.

**Comment by mcjaeger** [comment]
I think it can be closed now, as developers did not report recently about a mess with their artefacts.
