### ISSUE TITLE
The script program part of Component name can be set and executed when the component is registered.

### ISSUE THREAD

**Issue by KoukiHama** [eclipse/sw360#883]
For the safety of the system, I want to stop executing the registration like sample images.
Is there any way to stop this problem?

Branch: master (ff870d0) 
Ex. component  name ;  
`<script>function() { alert('Hello Hack SW360');</script>`
and Click [create component]

![image](https://user-images.githubusercontent.com/39894802/84238242-b5cdc800-ab35-11ea-89a4-cf73b313b4d5.png)

The Result
![image](https://user-images.githubusercontent.com/39894802/84237707-d0537180-ab34-11ea-98d5-8cecf8ff4438.png)

**Comment by JaideepPalit** [comment]
**Tested the issue. Some Observations**

- The script is not executed since the alert popup doesnot apear.

- It breaks the details page of component with console error while rendering the page.
![Screenshot from 2020-06-10 15-36-42](https://user-images.githubusercontent.com/56534710/84256263-4e157e00-ab31-11ea-97a5-f7a4c1c7775d.png)

- The code which appears in the screen is not sensitive and is part of the JSP which is send to User for rendering purpose upon request of Edit or View. Please refer below screenshot from Chrome Developer tool
![Screenshot from 2020-06-10 15-36-59](https://user-images.githubusercontent.com/56534710/84256686-deec5980-ab31-11ea-9cce-75d62012b841.png)

- It works fine in list all components page. Similar behaviour should be replicated in Details page
![Screenshot from 2020-06-10 15-42-54](https://user-images.githubusercontent.com/56534710/84256793-080cea00-ab32-11ea-8d34-ef88acd6c1e3.png)

**Comment by KoukiHama** [comment]
I checked this issue is solved in latest sw360.
