### ISSUE TITLE
Release SW360 in Maven

### ISSUE THREAD

**Issue by neubs-bsi** [eclipse/sw360#981]
SW360 should have a release in Maven

Todo:
- [x] make a weekly release in the eclipse maven
    - [x] create jenkins job with jenkinsfile
- [x] clear process

**Comment by blaumeiser-at-bosch** [comment]
@mcjaeger : I am currently investigating the options. It seems that in order to be able to run a sw360 build on the eclipse infrastructure requires that we deploy the build container based on the sw360dev.Dockerfile to the docker hub.

Would this be ok for you?

Should we apply to have it in the eclipse organization there or an own organization, open source projects can apply for an own team in docker hub?

**Comment by blaumeiser-at-bosch** [comment]
Discussion with the EF on building with a special docker container requirement:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=570045
